export const GET_ALL = 'GET_ALL';
export const FILTERED_BY_GENRES = 'FILTERED_BY_GENRES';
export const FILTERED_BY_SOURCE = 'FILTERED_BY_SOURCE';
export const ORDERED_BY_NAME = 'ORDERED_BY_NAME';
export const ORDERED_BY_RATING = 'ORDERED_BY_RATING';
export const CREATE_VIDEOGAME = 'CREATE_VIDEOGAME';